{"name": "test_login[case14]", "status": "passed", "attachments": [{"name": "log", "source": "c3535cb6-3599-4ba0-b073-707acd2f7a0d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case1", "value": "{'case_id': 5, 'title': '输入错误的账号', 'data': '(\"9i3jjLm3SxkpHakKWnTasg==\",\"ez27Us6DpzGoPNkb3FH/Mw==\",\"6666\",\"$2y$10$reArgS92v9zKSj.Z77yls.nqw0mxi1gVyEVzu.eYv9vT6/2DS8Z9q\",\"username\")', 'expected': '{\"code\": 0, \"msg\": \"账户密码错误\"}'}"}], "start": 1714393841991, "stop": 1714393844298, "uuid": "09b7eb93-d8be-45a9-bd3d-e7942ea303d0", "historyId": "0528eec490d524ed707b9e57171696a9", "testCaseId": "ee3b72303bf8fc3659dea4eab1f6b87e", "fullName": "test_ddt2.TestDdt#test_login", "labels": [{"name": "suite", "value": "test_ddt2"}, {"name": "subSuite", "value": "TestDdt"}, {"name": "host", "value": "LAPTOP-Q5VMTL8G"}, {"name": "thread", "value": "25284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_ddt2"}]}